/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalclinic.views;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import medicalclinic.DBConnection.DBConnection;
import medicalclinic.models.KartaPacjenta;
import medicalclinic.models.Pacjent;
import medicalclinic.models.Recepcjonistka;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Pawel
 */
public class Frame_RecepcjonistkaPacients extends javax.swing.JFrame {

    /**
     * Creates new form Frame_RecepcjonistkaPacients
     */
    public Recepcjonistka ty;
    
    public Frame_RecepcjonistkaPacients(Recepcjonistka r) {
        initComponents();
        this.ty = r;
        centre();
        updateTable();
    }
    
    public void centre() {
        Toolkit zestaw = Toolkit.getDefaultToolkit();
        Dimension wymiary = zestaw.getScreenSize();
        int wysokosc = wymiary.height;
        int szerokosc = wymiary.width;
        Point point = new Point(szerokosc / 2 - this.getWidth() / 2, wysokosc / 2 - this.getHeight() / 2);
        this.setLocation(point);
    }
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public void updateTable() {
        DBConnection db = DBConnection.getInstance();
        ResultSet rs = db.getUsersToTable("pacjent");
        if (rs != null) {
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } else {
            JOptionPane.showMessageDialog(null, "Błąd bazy danych");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medical Clinic");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane"));

        jLabel4.setText("Data urodzenia");

        jLabel7.setText("Login");

        jLabel5.setText("Telefon");

        jLabel2.setText("Imie");

        jLabel6.setText("Email");

        jLabel8.setText("Hasło");

        jTextField1.setEditable(false);

        jLabel3.setText("Nazwisko");

        jLabel1.setText("ID");

        jButton5.setText("Dodaj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Usuń");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Aktualizuj");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Aktualizuj hasło");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Wyczyść");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nazwisko rodowe");

        jLabel10.setText("PESEL");

        jLabel11.setText("Miejsce urodzenia");

        jLabel12.setText("Adres");

        jLabel13.setText("Płeć");

        jLabel14.setText("Wzrost");

        jLabel15.setText("Waga");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "k" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField15)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addComponent(jTextField13)
                            .addComponent(jTextField12)
                            .addComponent(jTextField10)
                            .addComponent(jTextField9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(29, 29, 29))
        );

        jButton1.setText("Odśwież");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });

        jLabel16.setText("Wyszukaj po PESELu");

        jButton2.setText("Zarządzanie wizytami");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Plik");

        jMenuItem1.setText("Wyjście");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int row = jTable1.getSelectedRow();
        if(jTable1.getValueAt(row, 0).toString()!=null) jTextField1.setText(jTable1.getValueAt(row, 0).toString());
        else jTextField1.setText("");
        if(jTable1.getValueAt(row, 1).toString()!=null) jTextField2.setText(jTable1.getValueAt(row, 1).toString());
        else jTextField2.setText("");
        if(jTable1.getValueAt(row, 2).toString()!=null) jTextField3.setText(jTable1.getValueAt(row, 2).toString());
        else jTextField3.setText("");
        if(jTable1.getValueAt(row, 3).toString()!=null) jTextField4.setText(jTable1.getValueAt(row, 3).toString());
        else jTextField4.setText("");
        if(jTable1.getValueAt(row, 4).toString()!=null) jTextField5.setText(jTable1.getValueAt(row, 4).toString());
        else jTextField5.setText("");
        if(jTable1.getValueAt(row, 5).toString()!=null) jTextField6.setText(jTable1.getValueAt(row, 5).toString());
        else jTextField6.setText("");
        if(jTable1.getValueAt(row, 6).toString()!=null) jTextField7.setText(jTable1.getValueAt(row, 6).toString());
        else jTextField7.setText("");
        if(jTable1.getValueAt(row, 7).toString()!=null) jTextField8.setText(jTable1.getValueAt(row, 7).toString());
        else jTextField8.setText("");
        if(jTable1.getValueAt(row, 8).toString()!=null) jTextField9.setText(jTable1.getValueAt(row, 8).toString());
        else jTextField9.setText("");
        if(jTable1.getValueAt(row, 9).toString()!=null) jTextField10.setText(jTable1.getValueAt(row, 9).toString());
        else jTextField10.setText("");
        if(jTable1.getValueAt(row, 10).toString()!=null) jComboBox1.setSelectedIndex((jTable1.getValueAt(row, 10).toString().equals("m"))?0:1);
        else jComboBox1.setSelectedIndex(0);
        if(jTable1.getValueAt(row, 11).toString()!=null) jTextField12.setText(jTable1.getValueAt(row, 11).toString());
        else jTextField12.setText("");
        jTextField13.setText("");
        KartaPacjenta k = DBConnection.getInstance().getKartaPacjenta(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
        jTextField14.setText(Integer.toString(k.getWzrost()));
        jTextField15.setText(Integer.toString(k.getWaga()));
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int row = jTable1.getSelectedRow();
            if(jTable1.getValueAt(row, 0).toString()!=null) jTextField1.setText(jTable1.getValueAt(row, 0).toString());
            else jTextField1.setText("");
            if(jTable1.getValueAt(row, 1).toString()!=null) jTextField2.setText(jTable1.getValueAt(row, 1).toString());
            else jTextField2.setText("");
            if(jTable1.getValueAt(row, 2).toString()!=null) jTextField3.setText(jTable1.getValueAt(row, 2).toString());
            else jTextField3.setText("");
            if(jTable1.getValueAt(row, 3).toString()!=null) jTextField4.setText(jTable1.getValueAt(row, 3).toString());
            else jTextField4.setText("");
            if(jTable1.getValueAt(row, 4).toString()!=null) jTextField5.setText(jTable1.getValueAt(row, 4).toString());
            else jTextField5.setText("");
            if(jTable1.getValueAt(row, 5).toString()!=null) jTextField6.setText(jTable1.getValueAt(row, 5).toString());
            else jTextField6.setText("");
            if(jTable1.getValueAt(row, 6).toString()!=null) jTextField7.setText(jTable1.getValueAt(row, 6).toString());
            else jTextField7.setText("");
            if(jTable1.getValueAt(row, 7).toString()!=null) jTextField8.setText(jTable1.getValueAt(row, 7).toString());
            else jTextField8.setText("");
            if(jTable1.getValueAt(row, 8).toString()!=null) jTextField9.setText(jTable1.getValueAt(row, 8).toString());
            else jTextField9.setText("");
            if(jTable1.getValueAt(row, 9).toString()!=null) jTextField10.setText(jTable1.getValueAt(row, 9).toString());
            else jTextField10.setText("");
            if(jTable1.getValueAt(row, 10).toString()!=null) jComboBox1.setSelectedIndex((jTable1.getValueAt(row, 10).toString().equals("m"))?0:1);
            else jComboBox1.setSelectedIndex(0);
            if(jTable1.getValueAt(row, 11).toString()!=null) jTextField12.setText(jTable1.getValueAt(row, 11).toString());
            else jTextField12.setText("");
            jTextField13.setText("");
            KartaPacjenta k = DBConnection.getInstance().getKartaPacjenta(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
            jTextField14.setText(Integer.toString(k.getWzrost()));
            jTextField15.setText(Integer.toString(k.getWaga()));
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Pacjent p = new Pacjent();
        p.setImie(jTextField2.getText());
        p.setNazwisko(jTextField3.getText());
        p.setNazwiskoRodowe(jTextField4.getText());
        p.setDataUrodzenia(jTextField5.getText());
        p.setPesel(jTextField6.getText());
        p.setTelefon(jTextField7.getText());
        p.setEmail(jTextField8.getText());
        p.setMiejsceUrodzenia(jTextField9.getText());
        p.setAdres(jTextField10.getText());
        p.setPlec(jComboBox1.getSelectedItem().toString());
        p.setLogin(jTextField12.getText());
        p.setHaslo(jTextField13.getText());
        KartaPacjenta k = new KartaPacjenta();
        k.setWzrost(Integer.parseInt(jTextField14.getText()));
        k.setWaga(Integer.parseInt(jTextField15.getText()));
        if(DBConnection.getInstance().checkLogin(p.getLogin())) {
            if (p.getHaslo().length() > 4) {
                if (ty.dodajPacjenta(p)) {
                    Pacjent p2 = DBConnection.getInstance().getPacjentByLogin(p.getLogin());
                    if(DBConnection.getInstance().dodajKartaPacjent(k, p2.getId())) {
                        JOptionPane.showMessageDialog(null, "Dodano");
                        updateTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Nie udało się dodać");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nie udało się dodać");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Zbyt krótkie hasło");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Podany login już istnieje");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz usunąć?") == JOptionPane.YES_OPTION) {
            //int row = jTable1.getSelectedRow();
            //int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            int id = Integer.parseInt(jTextField1.getText());
            if(DBConnection.getInstance().usunKartaPacjenta(id)) {
                if (ty.usunPacjenta(id)) {
                    JOptionPane.showMessageDialog(null, "Usunięto");
                    updateTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Nie udało się usunąć");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nie udało się usunąć");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Pacjent p = new Pacjent();
        p.setImie(jTextField2.getText());
        p.setNazwisko(jTextField3.getText());
        p.setNazwiskoRodowe(jTextField4.getText());
        p.setDataUrodzenia(jTextField5.getText());
        p.setPesel(jTextField6.getText());
        p.setTelefon(jTextField7.getText());
        p.setEmail(jTextField8.getText());
        p.setMiejsceUrodzenia(jTextField9.getText());
        p.setAdres(jTextField10.getText());
        p.setPlec(jComboBox1.getSelectedItem().toString());
        p.setLogin(jTextField12.getText());
        p.setHaslo(jTextField13.getText());
        KartaPacjenta k = new KartaPacjenta();
        k.setWzrost(Integer.parseInt(jTextField14.getText()));
        k.setWaga(Integer.parseInt(jTextField15.getText()));
        if (JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz zaktualizować dane?") == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jTextField1.getText());
            DBConnection db = DBConnection.getInstance();
            if (db.aktualizujPacjent(p, id)) {
                if(db.aktualizujKartaPacjenta(k, id)){
                    JOptionPane.showMessageDialog(null, "Zaktualizowano");
                    updateTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Nie udało się zaktualizować danych");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nie udało się zaktualizować danych");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz zaktualizować hasło?") == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jTextField1.getText());
            DBConnection db = DBConnection.getInstance();
            if(jTextField13.getText().length()>4) {
                if (db.aktualizujHaslo("pacjent", id, jTextField13.getText())) {
                    JOptionPane.showMessageDialog(null, "Zaktualizowano");
                    updateTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Nie udało się zaktualizować hasła");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Zbyt krótkie hasło");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pacjent p = new Pacjent();
        p.setId(Integer.parseInt(jTextField1.getText()));
        p.setImie(jTextField2.getText());
        p.setNazwisko(jTextField3.getText());
        p.setNazwiskoRodowe(jTextField4.getText());
        p.setDataUrodzenia(jTextField5.getText());
        p.setPesel(jTextField6.getText());
        p.setTelefon(jTextField7.getText());
        p.setEmail(jTextField8.getText());
        p.setMiejsceUrodzenia(jTextField9.getText());
        p.setAdres(jTextField10.getText());
        p.setPlec(jComboBox1.getSelectedItem().toString());
        p.setLogin(jTextField12.getText());
        new Frame_RecepcjonistkaWizyty(ty,p).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        for(int i=0;i<jTable1.getRowCount();i++) {
            if(jTable1.getValueAt(i, 5).toString().equals(jTextField11.getText())) {
                if(jTable1.getValueAt(i, 0).toString()!=null) jTextField1.setText(jTable1.getValueAt(i, 0).toString());
                else jTextField1.setText("");
                if(jTable1.getValueAt(i, 1).toString()!=null) jTextField2.setText(jTable1.getValueAt(i, 1).toString());
                else jTextField2.setText("");
                if(jTable1.getValueAt(i, 2).toString()!=null) jTextField3.setText(jTable1.getValueAt(i, 2).toString());
                else jTextField3.setText("");
                if(jTable1.getValueAt(i, 3).toString()!=null) jTextField4.setText(jTable1.getValueAt(i, 3).toString());
                else jTextField4.setText("");
                if(jTable1.getValueAt(i, 4).toString()!=null) jTextField5.setText(jTable1.getValueAt(i, 4).toString());
                else jTextField5.setText("");
                if(jTable1.getValueAt(i, 5).toString()!=null) jTextField6.setText(jTable1.getValueAt(i, 5).toString());
                else jTextField6.setText("");
                if(jTable1.getValueAt(i, 6).toString()!=null) jTextField7.setText(jTable1.getValueAt(i, 6).toString());
                else jTextField7.setText("");
                if(jTable1.getValueAt(i, 7).toString()!=null) jTextField8.setText(jTable1.getValueAt(i, 7).toString());
                else jTextField8.setText("");
                if(jTable1.getValueAt(i, 8).toString()!=null) jTextField9.setText(jTable1.getValueAt(i, 8).toString());
                else jTextField9.setText("");
                if(jTable1.getValueAt(i, 9).toString()!=null) jTextField10.setText(jTable1.getValueAt(i, 9).toString());
                else jTextField10.setText("");
                if(jTable1.getValueAt(i, 10).toString()!=null) jComboBox1.setSelectedIndex((jTable1.getValueAt(i, 10).toString().equals("m"))?0:1);
                else jComboBox1.setSelectedIndex(0);
                if(jTable1.getValueAt(i, 11).toString()!=null) jTextField12.setText(jTable1.getValueAt(i, 11).toString());
                else jTextField12.setText("");
                jTextField13.setText("");
                KartaPacjenta k = DBConnection.getInstance().getKartaPacjenta(Integer.parseInt(jTable1.getValueAt(i, 0).toString()));
                jTextField14.setText(Integer.toString(k.getWzrost()));
                jTextField15.setText(Integer.toString(k.getWaga()));
                break;
            }
            else {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jComboBox1.setSelectedIndex(0);
                jTextField12.setText("");
                jTextField13.setText("");
                jTextField14.setText("");
                jTextField15.setText("");
            }
        }
    }//GEN-LAST:event_jTextField11KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_RecepcjonistkaPacients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_RecepcjonistkaPacients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_RecepcjonistkaPacients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_RecepcjonistkaPacients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
