package medicalclinic.views;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import medicalclinic.models.Sesja;

public class Frame_Logowanie extends javax.swing.JFrame {

    public Sesja s;
    
    public Frame_Logowanie() {
        initComponents();
        s = new Sesja();
        centre();
    }
    public void centre() {
        Toolkit zestaw = Toolkit.getDefaultToolkit();
        Dimension wymiary = zestaw.getScreenSize();
        int wysokosc = wymiary.height;
        int szerokosc = wymiary.width;
        Point point = new Point(szerokosc/2-this.getWidth()/2, wysokosc/2-this.getHeight()/2);
        this.setLocation(point);
    }
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldLogin = new javax.swing.JTextField();
        passwordFieldHaslo = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonZaloguj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Logowanie");
        setResizable(false);

        textFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldLoginKeyPressed(evt);
            }
        });

        passwordFieldHaslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldHasloKeyPressed(evt);
            }
        });

        jLabel1.setText("Login");

        jLabel2.setText("Hasło");

        buttonZaloguj.setText("Zaloguj");
        buttonZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZalogujActionPerformed(evt);
            }
        });
        buttonZaloguj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonZalogujKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Logowanie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonZaloguj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldLogin)
                            .addComponent(passwordFieldHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordFieldHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(buttonZaloguj)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZalogujActionPerformed
        String login = textFieldLogin.getText();
        String haslo = passwordFieldHaslo.getText();
        String result = s.zaloguj(login, haslo);
        if(result.startsWith("true")) {
            close();
            if(result.endsWith("admin")) new Frame_AdminStart(s.getAdmin(), s).setVisible(true);
            else if(result.endsWith("pacjent")) new Frame_PacjentStart(s.getPacjent(), s).setVisible(true);
            else if(result.endsWith("recepcjonistka")) new Frame_RecepcjonistkaStart(s.getRecepcjonistka(), s).setVisible(true);
            else if(result.endsWith("lekarz")) new Frame_LekarzStart(s.getLekarz(), s).setVisible(true);
            else if(result.endsWith("pielegniarka")) new Frame_PielegniarkaStart(s.getPielegniarka(), s).setVisible(true);
        }
        else if(result.equals("false")){
            JOptionPane.showMessageDialog(null, "Błędny login lub hasło");
            passwordFieldHaslo.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Wystąpił błąd podczas logowania");
        }
    }//GEN-LAST:event_buttonZalogujActionPerformed

    private void textFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldLoginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) buttonZaloguj.doClick();
    }//GEN-LAST:event_textFieldLoginKeyPressed

    private void passwordFieldHasloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldHasloKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) buttonZaloguj.doClick();
    }//GEN-LAST:event_passwordFieldHasloKeyPressed

    private void buttonZalogujKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonZalogujKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) buttonZaloguj.doClick();
    }//GEN-LAST:event_buttonZalogujKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Logowanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonZaloguj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordFieldHaslo;
    private javax.swing.JTextField textFieldLogin;
    // End of variables declaration//GEN-END:variables
}
