/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalclinic.views;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import medicalclinic.models.Sesja;

/**
 *
 * @author Pawel
 */
public class Frame_ZmienHaslo extends javax.swing.JFrame {

    /**
     * Creates new form Frame_ZmienHaslo
     */
    public Sesja s;

    public Frame_ZmienHaslo(Sesja s) {
        initComponents();
        this.s = s;
        centre();
    }

    public void centre() {
        Toolkit zestaw = Toolkit.getDefaultToolkit();
        Dimension wymiary = zestaw.getScreenSize();
        int wysokosc = wymiary.height;
        int szerokosc = wymiary.width;
        Point point = new Point(szerokosc / 2 - this.getWidth() / 2, wysokosc / 2 - this.getHeight() / 2);
        this.setLocation(point);
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zmiana hasła - Medical Clinic");
        setResizable(false);

        jLabel1.setText("Stare hasło:");

        jLabel2.setText("Nowe hasło:");

        jLabel3.setText("Powtórz hasło:");

        jButton1.setText("Zmień");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2)
                            .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String p1 = jPasswordField1.getText();
        String p2 = jPasswordField2.getText();
        String p3 = jPasswordField3.getText();
        if(p2.length()>4) {
            if (s.getTypUzytkownika().equals("recepcjonistka")) {
                if (p1 != null && p2 != null && p3 != null) {
                    if (p2.equals(p3)) {
                        if (p1.equals(s.getRecepcjonistka().getHaslo())) {
                            if (s.getRecepcjonistka().zmienHaslo(p1, p2)) {
                                JOptionPane.showMessageDialog(null, "Gotowe");
                                close();
                            } else {
                                JOptionPane.showMessageDialog(null, "Nie udało się zmienić hasła");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Podane stare hasło jest błędne");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Podane hasła są różne");
                    }
                }
            }
            else if(s.getTypUzytkownika().equals("admin")) {
                if (p1 != null && p2 != null && p3 != null) {
                    if (p2.equals(p3)) {
                        if (p1.equals(s.getAdmin().getHaslo())) {
                            if (s.getAdmin().zmienHaslo(p1, p2)) {
                                JOptionPane.showMessageDialog(null, "Gotowe");
                                close();
                            } else {
                                JOptionPane.showMessageDialog(null, "Nie udało się zmienić hasła");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Podane stare hasło jest błędne");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Podane hasła są różne");
                    }
                }
            }
            else if(s.getTypUzytkownika().equals("pacjent")) {
                if (p1 != null && p2 != null && p3 != null) {
                    if (p2.equals(p3)) {
                        if (p1.equals(s.getPacjent().getHaslo())) {
                            if (s.getPacjent().zmienHaslo(p1, p2)) {
                                JOptionPane.showMessageDialog(null, "Gotowe");
                                close();
                            } else {
                                JOptionPane.showMessageDialog(null, "Nie udało się zmienić hasła");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Podane stare hasło jest błędne");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Podane hasła są różne");
                    }
                }
            }
            else if(s.getTypUzytkownika().equals("lekarz")) {
                if (p1 != null && p2 != null && p3 != null) {
                    if (p2.equals(p3)) {
                        if (p1.equals(s.getLekarz().getHaslo())) {
                            if (s.getLekarz().zmienHaslo(p1, p2)) {
                                JOptionPane.showMessageDialog(null, "Gotowe");
                                close();
                            } else {
                                JOptionPane.showMessageDialog(null, "Nie udało się zmienić hasła");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Podane stare hasło jest błędne");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Podane hasła są różne");
                    }
                }
            }
            else if(s.getTypUzytkownika().equals("pielegniarka")) {
                if (p1 != null && p2 != null && p3 != null) {
                    if (p2.equals(p3)) {
                        if (p1.equals(s.getPielegniarka().getHaslo())) {
                            if (s.getPielegniarka().zmienHaslo(p1, p2)) {
                                JOptionPane.showMessageDialog(null, "Gotowe");
                                close();
                            } else {
                                JOptionPane.showMessageDialog(null, "Nie udało się zmienić hasła");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Podane stare hasło jest błędne");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Podane hasła są różne");
                    }
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Nowe hasło jest zbyt krótkie");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jPasswordField3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ZmienHaslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ZmienHaslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ZmienHaslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ZmienHaslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables
}
